Chore/#tc 13 add dockerfile for admin page
treecreate/webstore pull request #223
Opened 2021-11-16 19:45 UTC by IroniX2

### This pull request closes:

✔️ Closes: N/A
🏁 Jira Issue: [TC-13](https://treecreate.atlassian.net/jira/software/c/projects/TC/boards/1?selectedIssue=TC-19)

### Which service(s) does this issue affect:

- [ ] 🛰️ API
- [ ] 🛒 webstore
- [x] 🎓 admin-page

### Types of changes

- [x] 🐛 Bug fix (a non-breaking change which fixes an issue)
- [ ] 🧱 New feature (a non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🤖 CI/CD (a change to the CI/CD pipeline)
- [ ] ⚗️ Refactoring (an update to some already existing code)

### Documentation Updates

- [x] 📂 No need for updates
- [ ] 📁 Requires an update ( _not done within this issue_ )
- [ ] 🗃️ Has been updated ( _done within this issue_ )

### Testing checklist

- [x] 💪 Manual tests
- [ ] 🔧 Automatic tests

#### Browser compatibility - _**[**Frontend only**]**_

- [ ] Tested on Safari
- [ ] Tested on Chrome
- [ ] Tested on Mozilla Firefox

### What changes have been done within this issue?

Changed webstore's Dockerfile to use new system.
Removed package.json's postbuild tag

### How should this be manually tested?

Run the project and Dockerfiles

### Screenshots or example usage

2021-11-24 11:10 UTC, IroniX2 commented on .deploy/admin-page/Dockerfile
> -
no longer needed

2021-11-24 11:11 UTC, IroniX2 commented on .deploy/webstore/Dockerfile
> +FROM node:lts-alpine3.14 AS builder
smol and zoom

2021-11-24 11:12 UTC, IroniX2 commented on package.json
> +    "postinstall": "ngcc"
Fixed postinstall script

2021-11-25 13:17 UTC, IroniX2 commented on .deploy/admin-page/Dockerfile
> -# Set required ENVs
moved under ENV for efficiency

2021-11-25 13:19 UTC, IroniX2 commented on package.json
> +    "typescript": "4.4.4"
These dependencies had to be moved here as they are required to build the prod version of webstore and admin-page

2021-11-25 13:20 UTC, IroniX2 commented
ready for review!

2021-11-25 18:57 UTC, Kwandes requested changes
I'm doing extensive testing of the branch making sure everything works correctly
But in terms of code alone, it looks good, and the images build
One note though: You may have gitignored the package-lock.json, you have to manually remove it since it is still tracked (once a file is added to git it gets tracked and has to be manually deleted)
Oh, and update your branch

2021-11-25 19:07 UTC, Kwandes commented
When deployed to staging the webstore app fails to load properly:
![image](https://user-images.githubusercontent.com/22862227/143491321-8e38d89f-83f5-44a2-a36e-9917aea350b6.png)
Admin works fine
When running locally via nx or running the docker image locally it works fine
Haven't tested deployed prod for obvious reasons

2021-11-26 13:29 UTC, Kwandes approved these changes
🚀

2021-11-26 18:09 UTC, merged